# Chicago

Let's just get this out of the way – I loved staying in Chicago the past 7 months. I have learned a lot about the local culture, the art scene, food and things like zines. Heck, I became a foodie after this! I think I have tried to check out as many places and attend as many events as possible. Akin to Cards Against Humanity's [fav list](http://chicago.cardsagainsthumanity.com/), here is my run down of things worth checking out[^*]. 

## Donuts and Pastries

### Lost Larson

Swedish-inspired pastries that are on a whole different level. I haven't tried anything better than their stuff and it's one of the things I miss the most from Chicago. I would avoid the Pain au Chocolat's (or what they call chocolate croissants for some reason), but otherwise you can't go wrong there. 

### Doughnut Vault

Get there early! The donuts are big and juicy, and the experience of buying from a hole in the wall type of place is also fun!

### Stan's Donuts

Everyone recommends them, and for good reason. My favourites are the Red Velvet, the Marshmallow Pocket and the Cinammon Roll.

### First Slice Pie Cafe

Settled in a former residential appartment, First Slice feels like home. They focus a lot on the local community and are an establishment that I kept coming back to. The French Silk was okay, but otherwise the pies are delicious.

### Chiu Quon Bakery

These may not be up everybody's wheelhouse, but I think these are the best Chinese pastries Chicago has to offer. I loved the BBQ pork bao and the egg yolk based pastries. 

### Do-Rite Donuts

Old school style (if you don't know what that means, definitely go!) donuts. If you get them fresh, they simply melt in your mouth. I haven't had a melting donut before!

## Bookstores

### Seminary Co-op

If a bookstore could be a cultural establishment, this would be it. They host events fairly often and they even have a podcast [Open Stacks](https://www.semcoop.com/open-stacks). If I could build the perfect bookstore, this would be very close.

### Quimby's

The Zine Capital in Chicago! They host monthly zine events and if you want to grab graphic novels or anything off-the-wall weird, this is the place to check out.

### Women & Children First

Their focus is feminist literature but they have an excellent general selection as well. Also, they host quite a lot of book events. Usually, if there is an author in town, you can be sure there will be an event at W&CF.

### Myopic Books

A used bookstore spanning three floors. The prices are high keeping in mind this is a used bookstore, but this is the place to find anything out-of-print. Found Lithuanian cultural studies!

### The Dial Bookshop

A fine selection of books, but the best part is getting to the bookshop as the elevator has an operator!

## Theatre and Comedy

### The Neo-Futurists

I have no idea how but I went to their Infinite Wrench five times. The group definitely pushes the limits of what comedy and theatre is, with a lot of fourth wall breaking and subversion. Definitely worth checking out.

### Improvised Shakespeare

Improv in iambic pentameter - not as edgy as everything else on the else, but a great source of entertainment nonetheless!

### Mocrep

They blew my mind during the Chicago Puppet Fest. 

### Paper Machete

A topical comedy blunder at the Green Mill. 

### Cards Against Humanity

They are neither a comedy nor a theatre group but they do host stand-up and game events often. Follow their events and be sure to go, they gather the most interesting crowds!

## Museums and Cultural Spots

### Art Institute of Chicago

I know this is an obvious place to check out but if you are planning to live in Chicago for half a year, get the membership pass! Evening lectures, early viewing and free coffee more than make up for the price. Since the Institute has a high exhibition turnaround, you naturally wanna visit the museum often.

### Museum of Contemporary Art

Now that summer is here, MCA is hosting so many events I am heartbroken. Look out for free days when they have new exhibitions!

### The Woolly Mammoth

This is a shop but the collection borders a museum! The owner is a great guy to talk to.

### Riverboat Architecture Tour

No better way to save time than to take a boat and see most of the architectural marvels of the city. Definitely worth the price.

### Harold Washington Library

Incredibly beautiful - if there is an exhibition or an event going on, it is definitely worth the trip.

### The Hideout and The Boxcar

In addition to Sofar Sounds, these places are sure to have a cosy evening event happening.

## Coffee

I'll preface this by saying that the North-side lacks good coffee spots. Most spots are located on the Blue Line or around the Pilsen area. 

### Osmium

First of all, the interior itself is already worth checking out. Second, the coffee is good. Loved their chais!

### Ipsento 606

Loved their tiny donuts and the park just outside their windows is awesome to enjoy the weather!

### Wormhole Coffee

Video game themed cafe. They have a Delorean inside and they serve peanut butter lattes - super sweet but definitely something to try.

### First Sip Cafe

I would probably not recommend this due price and quality ratio but they serve lattes with ube and turmeric, so it does receive an honorable mention.

### Coffee People Recommend

Other places people include are Gaslight, Two-Hearted Queen and Cafe Jumping Bean.

## Food

Food is a tricky subject to untangle because Chicago has an extremely diverse offering. I don't think I can make top 5 lists for specific types of restaurants, so this is a general list of places I enjoyed:

* Small Cheval - cheaper and better than Au Cheval;
* Nha Hang Vietnam - family restaurant that serves really good pho;
* Edgewater Tacos - fish tacos to die for!
* Antique Taco - wonderful tacos and horchata;
* Fat Chris's Pizza and Such - 12 USD pizza buffet, well worth the money
* Taste of Lebanon - hole in the wall type of place for delicious wraps
* Ras Dashen - Ethiopian place, bring friends!
* Chicago's Dog House - can't get enough of their variety of dogs
* Little Goat Diner - easily one of the best burgers I had in my life
* Sultan's Market - cheap and delicious pitas
* Piece Brewery - I want to say pricy, but still really good pizza
* Violet Hour - an approachable but classy cocktail place
* Lao Sze Chuan - my choice for Chinatown

All in all, I will definitely miss Chicago. The city is beautiful, the urban landscape is sprawling and it sure is my kind of town. I hope to see it again soon!

[^*]: I lived in Edgewater, so my list is slightly biased towards Andersonville and Argyle.

