# My Favourite Things Christmas

## Wearables

1. [Many Mornings](https://manymornings.com/en/) - Polish socks, comparable to Happy Socks.
1. [Daboti](https://www.daboti.lt/) - ties with Lithuanian motifs.

## Edibles

### Chocolate

1. [ach](https://www.achchocolate.com/lt/)
1. [Choco Collection](https://www.chocostore.eu/)
1. [La Naya](https://lanayachocolate.com/lt/pradinis/)
1. [Naive](https://chocolatenaive.com/)
1. [Amedei](https://amedei.it/en/)

### Coffee and Tea

1. [eteaket](https://www.eteaket.co.uk/)
1. [Coffee Loft](https://coffeeloft.lt/)
1. [Backstage Roasters](https://backstageroasters.com/)
1. [Huracan](https://huracan.lt/)
1. [Brew](https://www.brew.lt/collections/kavos-pupeles)
1. [Crooked Nose](https://www.brew.lt/collections/kavos-pupeles)

### Hot Sauce

1. [Chilli guys](https://www.facebook.com/chilliguysLT/)
1. [Kaunas sauce](https://www.facebook.com/kaunassauce/)

## Elektronika

1. [Tile](https://www.thetileapp.com/en-eu/)
1. [Mažas dėžių peilis](https://www.amazon.com/dp/B00M1XZXGU)
1. [AirTag](https://www.thetileapp.com/en-eu/)
1. [Smart power outlet](https://www.amazon.com/dp/B07MV7F26P/ref=psdc_6291368011_t1_B07BGT5RX6)
1. [Power Monitor](https://www.amazon.com/dp/B01CVMAK2M/)
1. [External Powerbank](https://www.amazon.co.uk/Mophie-PowerStation-X-Large-Portable-Charger-Black/dp/B07K4YQDLC/)
1. [Logitech Spotlight Remote](https://www.logitech.com/en-us/product/spotlight-presentation-remote)
1. [Mini Microscopes](https://www.amazon.com/gp/product/B00LAX52IQ/)
1. [3D Printing Pen](https://www.amazon.com/MYNT3D-Super-3D-Pen-Compatible)

# DIY

1. [Pinigai žaislo dėžėje](https://twitter.com/TwoClawsMedia/status/1210030954485633025)
2. [Receptas stiklainyje](https://www.tasteofhome.com/collection/recipes-for-gifts-in-a-jar/) - sausi ingredientai stiklainyje, dovanoji stiklainį ir receptą, kaip įmaišyti šlapią dalį.

# Virtuvėje

1. Praktiškai bet kas iš [Iittala](https://www.iittala.com/collections/iittala/tools/c/tools/intro) - tai yra brangu, bet tai yra daiktai, kurie tausos ilgą laiką.
2. Peiliai - [Siegel](https://medium.com/@pullnews/david-siegels-knife-porn-ea19f8553e79?) ir [ChefSteps](https://www.chefsteps.com/activities/the-chefsteps-kitchen-team-shares-their-favorite-knives) turi puikius gidus. Taip, peilių negalima dovanoti, taip, tai yra brangu, bet geras peilis gali tarnauti visą gyvenimą.
3. Maisto termometrai - nuvertinti daiktai, net pigiausias variantas, kuris nebūtinai tikslus, yra naudingas.
4. Butelių kamščiai - nusipirkau porą jų JAV ir, pasirodo, jų užsinorėjo visa giminė!
5. Mandolina - yra brangių, yra pigių, bet iš tikrųjų yra tik [Benriner](https://www.amazon.co.uk/s?k=mandoline+benriner&ref=nb_sb_noss).
6. [Articture](https://articture.com/) kitoms idėjoms.

# Dekoras

1. Georg Jansen kalėdiniai papuošimai - [these](https://www.georgjensen.com/global/christmas/scandinavian-christmas-decorations) labai tinka, jeigu keičiatės dovanomis prieš Kalėdas. Kiekvienais metais jie vis kitokie!
2. [Nordic Nest](https://www.nordicnest.com/) kitoms idėjoms.
3. [Vondels](https://www.vondels.com/en_US/) - parduodama Lietuvoje, bet galima užsisakyti tiesiogiai. Šmaikšti dovana, jeigu gavėjas turi pomėgį, pavyzdžiui, mėgsta [stalo žaidimus](https://www.vondels.com/en_US/p/ornament-glass-monopoly-playing-board-eng-h8cm-w-box/2651/) ar [taksus](https://www.vondels.com/en_US/p/ornament-glass-dachshund-with-christmas-hat-brown-h95cm/2439/).

## Komponentų pagerinimai

Stalo žaidimą galima pagerinti 3 būdams: pridėti stalo žaidimo papildymą, pridėti įmautes arba pagerinti komponentus. Pirmais dviem atvejais nustebinti žmogų sudėtinga, bet pagerinimai yra tai, ko kiekvienas nori, bet nebūtinai ryžtųsi sumokėti.

1. [BGG Store](https://boardgamegeekstore.com/)
2. [Spiele Material](https://www.spielematerial.de/en/)
2. [MeepleSource](https://www.meeplesource.com/proddetail.php?prod=WingspanUpgrade)
3. Taip pat galima internete rasti 3D modelius nemokamai (pavyzdžiui, Terraforming Mars lenteles), ir juos išspausdinti.
3. Etsy ;)
4. Šiems žaidimams leidėjai patys leidžia geresnius komponentus: [Scythe](https://stonemaier-games.myshopify.com/products/metal-coins-scythe-asia?variant=25456101190), [7 Wonders](https://shop.rprod.com/en/7-wonders-duel/52-7-wonders-duel-metal-coins.html), [Azul](https://www.nextmovegames.com/en/home/31-azul-joker-tiles.html)

## Aksesuarai

1. [Pirmo žaidėjo parinkėjas](https://www.amazon.co.uk/Ddfly-Shocking-Roulette-Detector-Reloaded/dp/B07G9H2QG8/)
2. [Kauliukų dubenėliai](https://www.deepcutstudio.com/product/dice-tray-bard/)


## Leidyklos

1. [And Other Stories](https://www.andotherstories.org/subscriptions/) - nepriklausoma leidykla, siūlanti prenumeratą. Prenumeratoriai periodiškai gauna knygą, o kiekvienos knygos gale yra prenumeratorių sąrašas, įskaitant ir tavo ar gavėjo! Jų knygų pasirinkimas neblogas ir periodiškai vertas dėmesio. Kaina priklauso nuo prenumeratos dydžio.
1. [RARA leidykla](https://raraleidykla.lt/) - anksčiau nebūčiau jų nurodęs, bet jie siūlo įsigyti visas ateinančių metų knygas iš anksto, todėl kaip ir __And Other Stories__, tai yra smagi staigmena knygų mylėtojui. Jeigu __Kitos knygos__ orientuojasi į anglų kalba išėjusių knygų topus, __RARA__ pasirinkimas orientuotas į modernią literatūrą, kuriai seniai reikėjo vertimo į lietuvių kalbą.
2. [New Eastern Europe](https://neweasterneurope.eu/subscribe/) - politinis žurnalas, orientuotas į Rytų Europą. Straipsnių kokybė iki šiol buvo gera ir pats žurnalas yra patogaus storo A5 formato, todėl tai galėtų būti per daug vietos neužimanti dovana.
3. [Phaidon](https://uk.phaidon.com/store/) - jų pasirinkime yra visko (skaityti: rinktis atsargiai!), bet kai kurios knygos yra spausdintos labai konkretiems žmonėms. Pavyzdžiui, gydytojui arba medicinos studentui ideali dovana galėtų būti [Anatomy book](https://uk.phaidon.com/store/general-non-fiction/anatomy-exploring-the-human-body-9780714879888/).
4. [Taschen](https://www.taschen.com/) - Taschen riečia nosį daugiau negu Phaidon vien žiūrint į jų kainas, bet Taschen dažnai siūlo savo knygas stambiais bei mažais (A5?) formatais. Mažo formato knygos yra įperkamos ir gali būti miela dovana ant kavos staliuko. Aš pats turiu [Soviet archtecture](https://www.taschen.com/pages/en/catalogue/architecture/all/49365/facts.frederic_chaubin_cccp.htm), kurią buvo įdomu pavartyti. Taip pat rekomenduoju knygą apie [gamtos istoriją](https://www.taschen.com/pages/en/catalogue/classics/all/05420/facts.seba_cabinet_of_natural_curiosities.htm).
5. [Stripe Press](https://press.stripe.com/) - prieinama tik JAV, knygos šiek tiek pretenzingos, bet pačių knygų kokybė yra viena geriausių, kokias teko matyti. Temos orientuotos į ekonomiką, progresą bei technologijas, bet jos paliečia labai įdomias temas. 
6. [Fantagraphics](https://www.fantagraphics.com/) - Black Friday nuolaidos neblogos, bet ašaroja akys nuo tiesioginio siuntimo į EU, todėl reikia žiūrėti į Amazon pasirinkimą. Leidyklos pasirinkimas man patinka - jie išleido __My Favourite Thing is Monsters__!


## Konkrečios knygos

1. Iliustruotos knygos - iliustruotos knygos neįpareigoja skaityti, o tiesiog gerėtis, todėl tai nėra sąžinę graužianti dovana kaip įprasta knyga. Iš pirmo žvilgsnio man patiko [Spineless](https://www.amazon.com/Spineless-Portraits-Marine-Invertebrates-Backbone/dp/1419710079/) ir [Seeking Leviathan](https://cswannphotography.com/book/).
2. Kulinarinės knygos - labai nuvertinta dovana, juolab kad dabar yra labai stiprus jų pasirinkimas. Bendrai, kiekvienais metais verta patikrinti [James Beard apdovanojimus](https://www.jamesbeard.org/blog/this-years-best-cookbooks). Aš pats rekomenduočiau [the Food of Sichuan](https://www.amazon.co.uk/Food-Sichuan-Fuchsia-Dunlop/dp/1408867559), labai girtą [Salt, Fat, Acid, Heat](https://www.amazon.co.uk/Salt-Fat-Acid-Heat-Mastering/dp/1782112308/)[^1] ir [The Last Course](https://www.amazon.co.uk/dp/037550429X/) arba [Sababa](https://www.amazon.co.uk/dp/0525533451/).




